#cloud-config
bootcmd:
  - rm -f /etc/systemd/network/*.network
  - systemctl stop systemd-networkd

write_files:
  - content: |
        eno_name=$(ip addr | grep eno | sed 's/.*\(eno.*\):.*/\1/' | head -n 1)
        cat > "/etc/systemd/network/10-dhcp-${eno_name}.network" << EOF
        [Match]
        Name=${eno_name}

        [Network]
        DNS=10.162.204.1

        [Address]
        Address=10.20.101.11/16

        [Route]
        Gateway=10.161.31.253
        EOF
        ip addr flush label "${eno_name}"
        systemctl restart systemd-networkd
        ip=`grep Address= /etc/systemd/network/10-dhcp-${eno_name}.network | sed 's/.*=\.*//' | sed 's/\/.*//'`
        echo ip
        c_ip=`ifconfig ${eno_name} | sed -n '/dr:/{;s/.*dr://;s/ .*//;p;}'`
        while [ "$ip" != "$c_ip" ]
        do
          ip addr flush label "${eno_name}"
          systemctl restart systemd-networkd
          c_ip=`ifconfig ${eno_name} | sed -n '/dr:/{;s/.*dr://;s/ .*//;p;}'`
          echo $c_ip
          sleep 1
        done
        ping -q -c 4 10.161.31.253
    owner: root:root
    permissions: 0644
    path: /tmp/init-network.sh

  - content: |
        eno_name=$(ip addr | grep eno | sed 's/.*\(eno.*\):.*/\1/' | head -n 1)
        ipAddress=`ifconfig ${eno_name} | sed -n '/dr:/{;s/.*dr://;s/ .*//;p;}'`
        etcdImage=quay.io/coreos/etcd:v2.0.8

        echo "Starting etcd"
        docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs -p 4001:4001 \
         -p 2380:2380 -p 2379:2379 \
         --restart=always \
         --name etcd ${etcdImage} \
         -name etcd0 \
         -advertise-client-urls http://${ipAddress}:2379,http://${ipAddress}:4001 \
         -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
         -initial-advertise-peer-urls http://${ipAddress}:2380 \
         -listen-peer-urls http://0.0.0.0:2380 \
         -initial-cluster etcd0=http://10.20.101.11:2380 \
         -initial-cluster-state new

        echo "done"
    owner: root:root
    permissions: 0644
    path: /tmp/start-etcd.sh

  - content: |
        retry_max="60"
        retry="0"
        while [ "$retry" -lt "$retry_max" ]
        do
          docker version
          if [ "$?" == "0" ]; then
            echo "Docker daemon is up and running!"
            break
          fi
          sleep 1
          retry=`expr $retry + 1`
        done

        if [ "$retry" -eq "$retry_max" ]
        then
          echo "Docker daemon is not up yet!"
        fi
    owner: root:root
    permissions: 0644
    path: /tmp/check-docker.sh

runcmd:
  - sh /tmp/init-network.sh
  - systemctl enable docker
  - systemctl start docker
  - sh /tmp/check-docker.sh
  - sh /tmp/start-etcd.sh > /var/log/etcd.log
